[2025-06-19T01:17:18.829+0000] {processor.py:161} INFO - Started process (PID=51385) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:17:18.830+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:17:18.831+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:17:18.831+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:17:18.834+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:17:18.833+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:17:18.835+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:17:18.851+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.029 seconds
[2025-06-19T01:17:49.370+0000] {processor.py:161} INFO - Started process (PID=51421) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:17:49.371+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:17:49.372+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:17:49.372+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:17:49.375+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:17:49.374+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:17:49.376+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:17:49.391+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.029 seconds
[2025-06-19T01:18:19.867+0000] {processor.py:161} INFO - Started process (PID=51457) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:18:19.868+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:18:19.869+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:18:19.869+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:18:19.872+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:18:19.871+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:18:19.872+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:18:19.887+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.028 seconds
[2025-06-19T01:18:50.462+0000] {processor.py:161} INFO - Started process (PID=51493) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:18:50.463+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:18:50.464+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:18:50.464+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:18:50.467+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:18:50.466+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:18:50.468+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:18:50.501+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.045 seconds
[2025-06-19T01:19:21.222+0000] {processor.py:161} INFO - Started process (PID=51535) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:19:21.223+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:19:21.224+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:19:21.224+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:19:21.228+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:19:21.227+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:19:21.229+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:19:21.247+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.036 seconds
[2025-06-19T01:19:51.840+0000] {processor.py:161} INFO - Started process (PID=51571) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:19:51.842+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:19:51.842+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:19:51.842+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:19:51.845+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:19:51.844+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:19:51.845+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:19:51.860+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.026 seconds
[2025-06-19T01:20:22.255+0000] {processor.py:161} INFO - Started process (PID=51607) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:20:22.256+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:20:22.257+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:20:22.256+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:20:22.259+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:20:22.259+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:20:22.260+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:20:22.275+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.027 seconds
[2025-06-19T01:20:52.727+0000] {processor.py:161} INFO - Started process (PID=51643) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:20:52.730+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:20:52.733+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:20:52.732+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:20:52.739+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:20:52.738+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:20:52.740+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:20:52.761+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.046 seconds
[2025-06-19T01:21:23.302+0000] {processor.py:161} INFO - Started process (PID=51679) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:21:23.303+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:21:23.304+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:21:23.304+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:21:23.307+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:21:23.306+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:21:23.308+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:21:23.324+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.030 seconds
[2025-06-19T01:21:54.192+0000] {processor.py:161} INFO - Started process (PID=51715) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:21:54.193+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:21:54.194+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:21:54.194+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:21:54.197+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:21:54.196+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:21:54.198+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:21:54.213+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.028 seconds
[2025-06-19T01:22:24.729+0000] {processor.py:161} INFO - Started process (PID=51751) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:22:24.731+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:22:24.733+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:22:24.733+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:22:24.736+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:22:24.735+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:22:24.737+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:22:24.751+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.031 seconds
[2025-06-19T01:22:55.340+0000] {processor.py:161} INFO - Started process (PID=51787) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:22:55.341+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:22:55.342+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:22:55.342+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:22:55.345+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:22:55.345+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:22:55.347+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:22:55.362+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.030 seconds
[2025-06-19T01:23:26.182+0000] {processor.py:161} INFO - Started process (PID=51823) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:23:26.183+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:23:26.184+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:23:26.184+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:23:26.186+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:23:26.186+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:23:26.187+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:23:26.201+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.027 seconds
[2025-06-19T01:23:56.763+0000] {processor.py:161} INFO - Started process (PID=51859) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:23:56.764+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:23:56.765+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:23:56.765+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:23:56.768+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:23:56.767+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:23:56.769+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:23:56.785+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.030 seconds
[2025-06-19T01:24:27.322+0000] {processor.py:161} INFO - Started process (PID=51895) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:24:27.323+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:24:27.324+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:24:27.324+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:24:27.327+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:24:27.326+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:24:27.327+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:24:27.341+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.026 seconds
[2025-06-19T01:24:57.817+0000] {processor.py:161} INFO - Started process (PID=51931) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:24:57.818+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:24:57.819+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:24:57.818+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:24:57.821+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:24:57.821+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:24:57.822+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:24:57.839+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.031 seconds
[2025-06-19T01:25:28.457+0000] {processor.py:161} INFO - Started process (PID=51967) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:25:28.458+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:25:28.459+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:25:28.459+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:25:28.462+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:25:28.461+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:25:28.463+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:25:28.481+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.031 seconds
[2025-06-19T01:25:59.020+0000] {processor.py:161} INFO - Started process (PID=52003) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:25:59.021+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:25:59.022+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:25:59.021+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:25:59.024+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:25:59.023+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:25:59.025+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:25:59.041+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.029 seconds
[2025-06-19T01:26:29.857+0000] {processor.py:161} INFO - Started process (PID=52039) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:26:29.858+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:26:29.859+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:26:29.859+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:26:29.863+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:26:29.862+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:26:29.864+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:26:29.882+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.032 seconds
[2025-06-19T01:27:00.303+0000] {processor.py:161} INFO - Started process (PID=52075) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:27:00.304+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:27:00.305+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:27:00.305+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:27:00.308+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:27:00.307+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:27:00.308+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:27:00.326+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.031 seconds
[2025-06-19T01:27:30.934+0000] {processor.py:161} INFO - Started process (PID=52111) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:27:30.935+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:27:30.936+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:27:30.936+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:27:30.939+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:27:30.938+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:27:30.940+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:27:30.955+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.030 seconds
[2025-06-19T01:28:01.447+0000] {processor.py:161} INFO - Started process (PID=52147) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:28:01.449+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:28:01.450+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:28:01.450+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:28:01.454+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:28:01.453+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:28:01.455+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:28:01.472+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.033 seconds
[2025-06-19T01:28:32.099+0000] {processor.py:161} INFO - Started process (PID=52183) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:28:32.100+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:28:32.101+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:28:32.101+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:28:32.104+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:28:32.104+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:28:32.106+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:28:32.124+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.034 seconds
[2025-06-19T01:29:02.834+0000] {processor.py:161} INFO - Started process (PID=52219) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:29:02.835+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:29:02.836+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:29:02.836+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:29:02.841+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:29:02.839+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:29:02.842+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:29:02.870+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.050 seconds
[2025-06-19T01:29:33.099+0000] {processor.py:161} INFO - Started process (PID=52255) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:29:33.101+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:29:33.102+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:29:33.101+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:29:33.105+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:29:33.104+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:29:33.106+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:29:33.129+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.041 seconds
[2025-06-19T01:30:03.326+0000] {processor.py:161} INFO - Started process (PID=52291) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:30:03.327+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:30:03.328+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:30:03.328+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:30:03.331+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:30:03.330+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:30:03.332+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:30:03.352+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.036 seconds
[2025-06-19T01:30:34.045+0000] {processor.py:161} INFO - Started process (PID=52327) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:30:34.046+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:30:34.047+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:30:34.046+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:30:34.049+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:30:34.048+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:30:34.050+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:30:34.065+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.027 seconds
[2025-06-19T01:31:04.562+0000] {processor.py:161} INFO - Started process (PID=52363) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:31:04.563+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:31:04.564+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:31:04.564+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:31:04.567+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:31:04.566+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:31:04.568+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:31:04.587+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.036 seconds
[2025-06-19T01:31:35.241+0000] {processor.py:161} INFO - Started process (PID=52399) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:31:35.243+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:31:35.245+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:31:35.244+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:31:35.249+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:31:35.247+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:31:35.250+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:31:35.274+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.044 seconds
[2025-06-19T01:32:05.904+0000] {processor.py:161} INFO - Started process (PID=52435) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:32:05.905+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:32:05.906+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:32:05.905+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:32:05.909+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:32:05.908+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:32:05.910+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:32:05.929+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.035 seconds
[2025-06-19T01:32:36.651+0000] {processor.py:161} INFO - Started process (PID=52471) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:32:36.652+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:32:36.654+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:32:36.653+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:32:36.657+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:32:36.656+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:32:36.658+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:32:36.678+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.037 seconds
[2025-06-19T01:33:07.335+0000] {processor.py:161} INFO - Started process (PID=52507) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:33:07.336+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:33:07.337+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:33:07.337+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:33:07.341+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:33:07.340+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:33:07.342+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:33:07.363+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.039 seconds
[2025-06-19T01:33:38.011+0000] {processor.py:161} INFO - Started process (PID=52543) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:33:38.013+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:33:38.015+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:33:38.014+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:33:38.020+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:33:38.018+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:33:38.022+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:33:38.055+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.058 seconds
[2025-06-19T01:34:08.720+0000] {processor.py:161} INFO - Started process (PID=52579) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:34:08.721+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:34:08.722+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:34:08.721+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:34:08.725+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:34:08.724+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:34:08.726+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:34:08.748+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.039 seconds
[2025-06-19T01:34:39.483+0000] {processor.py:161} INFO - Started process (PID=52615) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:34:39.484+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:34:39.486+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:34:39.485+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:34:39.489+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:34:39.488+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:34:39.490+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:34:39.512+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.040 seconds
[2025-06-19T01:35:10.172+0000] {processor.py:161} INFO - Started process (PID=52652) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:35:10.173+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:35:10.174+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:35:10.174+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:35:10.180+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:35:10.179+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:35:10.181+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:35:10.203+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.042 seconds
[2025-06-19T01:35:40.986+0000] {processor.py:161} INFO - Started process (PID=52688) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:35:40.988+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:35:40.990+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:35:40.989+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:35:40.995+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:35:40.994+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:35:40.997+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:35:41.026+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.052 seconds
[2025-06-19T01:36:11.799+0000] {processor.py:161} INFO - Started process (PID=52724) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:36:11.800+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:36:11.801+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:36:11.801+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:36:11.805+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:36:11.804+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:36:11.806+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:36:11.826+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.038 seconds
[2025-06-19T01:36:42.638+0000] {processor.py:161} INFO - Started process (PID=52760) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:36:42.639+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:36:42.641+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:36:42.640+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:36:42.645+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:36:42.644+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:36:42.646+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:36:42.668+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.039 seconds
[2025-06-19T01:37:13.190+0000] {processor.py:161} INFO - Started process (PID=52796) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:37:13.191+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:37:13.192+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:37:13.192+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:37:13.197+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:37:13.196+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:37:13.199+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:37:13.219+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.041 seconds
[2025-06-19T01:37:43.932+0000] {processor.py:161} INFO - Started process (PID=52832) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:37:43.934+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:37:43.935+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:37:43.935+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:37:43.938+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:37:43.937+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:37:43.939+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:37:43.963+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.041 seconds
[2025-06-19T01:38:14.752+0000] {processor.py:161} INFO - Started process (PID=52868) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:38:14.754+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:38:14.755+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:38:14.755+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:38:14.759+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:38:14.758+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:38:14.760+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:38:14.786+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.043 seconds
[2025-06-19T01:38:45.388+0000] {processor.py:161} INFO - Started process (PID=52905) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:38:45.389+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:38:45.391+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:38:45.390+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:38:45.394+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:38:45.393+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:38:45.395+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:38:45.418+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.042 seconds
[2025-06-19T01:39:16.048+0000] {processor.py:161} INFO - Started process (PID=52941) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:39:16.050+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:39:16.051+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:39:16.050+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:39:16.055+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:39:16.054+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:39:16.056+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:39:16.074+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.037 seconds
[2025-06-19T01:39:46.622+0000] {processor.py:161} INFO - Started process (PID=52977) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:39:46.623+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:39:46.625+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:39:46.624+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:39:46.629+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:39:46.627+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:39:46.630+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:39:46.651+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.039 seconds
[2025-06-19T01:40:17.250+0000] {processor.py:161} INFO - Started process (PID=53013) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:40:17.252+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:40:17.253+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:40:17.253+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:40:17.258+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:40:17.257+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:40:17.259+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:40:17.283+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.046 seconds
[2025-06-19T01:40:48.004+0000] {processor.py:161} INFO - Started process (PID=53049) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:40:48.005+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:40:48.006+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:40:48.006+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:40:48.010+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:40:48.008+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:40:48.011+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:40:48.032+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.037 seconds
[2025-06-19T01:41:18.550+0000] {processor.py:161} INFO - Started process (PID=53085) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:41:18.551+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:41:18.552+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:41:18.552+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:41:18.557+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:41:18.555+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:41:18.558+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:41:18.581+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.041 seconds
[2025-06-19T01:41:49.448+0000] {processor.py:161} INFO - Started process (PID=53121) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:41:49.450+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:41:49.451+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:41:49.451+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:41:49.455+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:41:49.454+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:41:49.456+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:41:49.477+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.039 seconds
[2025-06-19T01:42:20.291+0000] {processor.py:161} INFO - Started process (PID=53158) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:42:20.293+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:42:20.295+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:42:20.295+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:42:20.299+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:42:20.298+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:42:20.301+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:42:20.327+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.048 seconds
[2025-06-19T01:42:51.551+0000] {processor.py:161} INFO - Started process (PID=53194) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:42:51.561+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:42:51.570+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:42:51.570+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:42:51.589+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:42:51.587+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:42:51.601+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:42:51.644+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.115 seconds
[2025-06-19T01:43:22.031+0000] {processor.py:161} INFO - Started process (PID=53230) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:43:22.032+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:43:22.034+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:43:22.033+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:43:22.038+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:43:22.037+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:43:22.040+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:43:22.068+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.050 seconds
[2025-06-19T01:43:52.357+0000] {processor.py:161} INFO - Started process (PID=53266) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:43:52.358+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:43:52.359+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:43:52.359+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:43:52.364+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:43:52.362+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:43:52.365+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:43:52.389+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.043 seconds
[2025-06-19T01:44:22.539+0000] {processor.py:161} INFO - Started process (PID=53302) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:44:22.541+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:44:22.542+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:44:22.542+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:44:22.546+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:44:22.545+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:44:22.548+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:44:22.572+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.045 seconds
[2025-06-19T01:44:52.945+0000] {processor.py:161} INFO - Started process (PID=53345) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:44:52.946+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:44:52.948+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:44:52.947+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:44:52.952+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:44:52.951+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:44:52.954+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:44:52.979+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.045 seconds
[2025-06-19T01:45:23.304+0000] {processor.py:161} INFO - Started process (PID=53381) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:45:23.306+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:45:23.307+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:45:23.307+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:45:23.311+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:45:23.310+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:45:23.312+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:45:23.342+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.051 seconds
[2025-06-19T01:45:53.942+0000] {processor.py:161} INFO - Started process (PID=53417) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:45:53.943+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:45:53.946+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:45:53.945+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:45:53.952+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:45:53.951+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:45:53.953+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:45:53.989+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.063 seconds
[2025-06-19T01:46:24.574+0000] {processor.py:161} INFO - Started process (PID=53453) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:46:24.575+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:46:24.577+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:46:24.576+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:46:24.582+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:46:24.580+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:46:24.583+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:46:24.613+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.053 seconds
[2025-06-19T01:46:54.858+0000] {processor.py:161} INFO - Started process (PID=53489) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:46:54.859+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:46:54.861+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:46:54.860+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:46:54.865+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:46:54.864+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:46:54.867+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:46:54.896+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.050 seconds
[2025-06-19T01:47:25.511+0000] {processor.py:161} INFO - Started process (PID=53525) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:47:25.512+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:47:25.514+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:47:25.514+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:47:25.520+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:47:25.518+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:47:25.521+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:47:25.547+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.047 seconds
[2025-06-19T01:47:55.707+0000] {processor.py:161} INFO - Started process (PID=53561) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:47:55.709+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:47:55.710+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:47:55.710+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:47:55.715+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:47:55.713+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:47:55.716+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:47:55.746+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.052 seconds
[2025-06-19T01:48:26.287+0000] {processor.py:161} INFO - Started process (PID=53597) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:48:26.291+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:48:26.299+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:48:26.298+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:48:26.306+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:48:26.304+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:48:26.311+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:48:26.343+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.069 seconds
[2025-06-19T01:48:56.590+0000] {processor.py:161} INFO - Started process (PID=53632) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:48:56.592+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:48:56.593+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:48:56.593+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:48:56.598+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:48:56.596+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:48:56.600+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:48:56.629+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.052 seconds
[2025-06-19T01:49:26.779+0000] {processor.py:161} INFO - Started process (PID=53668) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:49:26.781+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:49:26.783+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:49:26.783+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:49:26.788+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:49:26.786+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:49:26.789+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:49:26.819+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.054 seconds
[2025-06-19T01:49:57.172+0000] {processor.py:161} INFO - Started process (PID=53705) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:49:57.173+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:49:57.175+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:49:57.174+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:49:57.179+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:49:57.178+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:49:57.180+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:49:57.207+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.047 seconds
[2025-06-19T01:50:27.449+0000] {processor.py:161} INFO - Started process (PID=53741) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:50:27.450+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:50:27.452+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:50:27.452+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:50:27.456+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:50:27.455+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:50:27.457+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:50:27.482+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.043 seconds
[2025-06-19T01:50:57.777+0000] {processor.py:161} INFO - Started process (PID=53777) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:50:57.779+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:50:57.781+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:50:57.780+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:50:57.785+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:50:57.783+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:50:57.786+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:50:57.811+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.046 seconds
[2025-06-19T01:51:28.382+0000] {processor.py:161} INFO - Started process (PID=53814) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:51:28.384+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:51:28.385+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:51:28.385+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:51:28.390+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:51:28.388+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:51:28.392+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:51:28.424+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.053 seconds
[2025-06-19T01:51:59.018+0000] {processor.py:161} INFO - Started process (PID=53850) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:51:59.020+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:51:59.021+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:51:59.021+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:51:59.026+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:51:59.025+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:51:59.029+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:51:59.057+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.051 seconds
[2025-06-19T01:52:29.778+0000] {processor.py:161} INFO - Started process (PID=53886) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:52:29.779+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:52:29.781+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:52:29.781+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:52:29.787+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:52:29.785+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:52:29.788+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:52:29.815+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.055 seconds
[2025-06-19T01:53:00.157+0000] {processor.py:161} INFO - Started process (PID=53922) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:53:00.158+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:53:00.159+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:53:00.159+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:53:00.163+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:53:00.162+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:53:00.164+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:53:00.185+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.040 seconds
[2025-06-19T01:53:30.483+0000] {processor.py:161} INFO - Started process (PID=53958) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:53:30.484+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:53:30.485+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:53:30.485+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:53:30.489+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:53:30.488+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:53:30.490+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:53:30.511+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.037 seconds
[2025-06-19T01:54:00.691+0000] {processor.py:161} INFO - Started process (PID=53995) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:54:00.692+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:54:00.693+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:54:00.693+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:54:00.697+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:54:00.696+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:54:00.698+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:54:00.716+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.034 seconds
[2025-06-19T01:54:31.082+0000] {processor.py:161} INFO - Started process (PID=54031) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:54:31.084+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:54:31.086+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:54:31.085+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:54:31.090+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:54:31.088+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:54:31.091+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:54:31.113+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.042 seconds
[2025-06-19T01:55:01.471+0000] {processor.py:161} INFO - Started process (PID=54067) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:55:01.472+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:55:01.473+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:55:01.473+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:55:01.476+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:55:01.475+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:55:01.477+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:55:01.498+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.036 seconds
[2025-06-19T01:55:31.858+0000] {processor.py:161} INFO - Started process (PID=54103) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:55:31.859+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:55:31.860+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:55:31.860+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:55:31.864+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:55:31.863+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:55:31.865+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:55:31.884+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.036 seconds
[2025-06-19T01:56:02.068+0000] {processor.py:161} INFO - Started process (PID=54139) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:56:02.070+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:56:02.072+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:56:02.072+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:56:02.077+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:56:02.076+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:56:02.079+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:56:02.099+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.042 seconds
[2025-06-19T01:56:32.445+0000] {processor.py:161} INFO - Started process (PID=54175) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:56:32.446+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:56:32.447+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:56:32.447+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:56:32.450+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:56:32.450+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:56:32.451+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:56:32.470+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.035 seconds
[2025-06-19T01:57:02.713+0000] {processor.py:161} INFO - Started process (PID=54211) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:57:02.714+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:57:02.715+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:57:02.715+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:57:02.719+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:57:02.718+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:57:02.720+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:57:02.738+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.035 seconds
[2025-06-19T01:57:33.133+0000] {processor.py:161} INFO - Started process (PID=54247) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:57:33.135+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:57:33.137+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:57:33.137+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:57:33.149+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:57:33.148+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:57:33.150+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:57:33.168+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.045 seconds
[2025-06-19T01:58:03.592+0000] {processor.py:161} INFO - Started process (PID=54283) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:58:03.593+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:58:03.595+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:58:03.594+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:58:03.598+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:58:03.597+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:58:03.600+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:58:03.623+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.039 seconds
[2025-06-19T01:58:33.963+0000] {processor.py:161} INFO - Started process (PID=54319) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:58:33.964+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:58:33.965+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:58:33.965+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:58:33.968+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:58:33.967+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:58:33.969+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:58:33.990+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.036 seconds
[2025-06-19T01:59:04.286+0000] {processor.py:161} INFO - Started process (PID=54355) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:59:04.287+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:59:04.288+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:59:04.288+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:59:04.292+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:59:04.291+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:59:04.293+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:59:04.313+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.038 seconds
[2025-06-19T01:59:34.798+0000] {processor.py:161} INFO - Started process (PID=54391) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:59:34.800+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T01:59:34.801+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:59:34.800+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:59:34.804+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:59:34.803+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:59:34.805+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T01:59:34.825+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.037 seconds
[2025-06-19T02:00:05.029+0000] {processor.py:161} INFO - Started process (PID=54427) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T02:00:05.030+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T02:00:05.032+0000] {logging_mixin.py:188} INFO - [2025-06-19T02:00:05.031+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T02:00:05.035+0000] {logging_mixin.py:188} INFO - [2025-06-19T02:00:05.034+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T02:00:05.037+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T02:00:05.054+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.033 seconds
[2025-06-19T02:00:35.365+0000] {processor.py:161} INFO - Started process (PID=54463) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T02:00:35.366+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py for tasks to queue
[2025-06-19T02:00:35.368+0000] {logging_mixin.py:188} INFO - [2025-06-19T02:00:35.367+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T02:00:35.371+0000] {logging_mixin.py:188} INFO - [2025-06-19T02:00:35.370+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py", line 28, in <module>
    from airflow.providers.standard.operators.trigger_dagrun import TriggerDagRunOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T02:00:35.372+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py
[2025-06-19T02:00:35.390+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_trigger_controller_dag.py took 0.032 seconds
