[2025-06-19T01:17:19.180+0000] {processor.py:161} INFO - Started process (PID=51394) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:17:19.182+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:17:19.182+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:17:19.182+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:17:19.185+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:17:19.185+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:17:19.186+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:17:19.200+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.027 seconds
[2025-06-19T01:17:49.769+0000] {processor.py:161} INFO - Started process (PID=51430) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:17:49.770+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:17:49.771+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:17:49.771+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:17:49.774+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:17:49.773+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:17:49.775+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:17:49.791+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.028 seconds
[2025-06-19T01:18:20.207+0000] {processor.py:161} INFO - Started process (PID=51466) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:18:20.209+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:18:20.210+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:18:20.210+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:18:20.213+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:18:20.212+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:18:20.214+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:18:20.228+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.027 seconds
[2025-06-19T01:18:51.001+0000] {processor.py:161} INFO - Started process (PID=51502) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:18:51.002+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:18:51.004+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:18:51.003+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:18:51.007+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:18:51.006+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:18:51.007+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:18:51.024+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.032 seconds
[2025-06-19T01:19:21.645+0000] {processor.py:161} INFO - Started process (PID=51544) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:19:21.646+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:19:21.647+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:19:21.647+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:19:21.650+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:19:21.649+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:19:21.650+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:19:21.664+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.027 seconds
[2025-06-19T01:19:52.161+0000] {processor.py:161} INFO - Started process (PID=51580) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:19:52.163+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:19:52.164+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:19:52.164+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:19:52.167+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:19:52.166+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:19:52.168+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:19:52.186+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.033 seconds
[2025-06-19T01:20:22.603+0000] {processor.py:161} INFO - Started process (PID=51616) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:20:22.605+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:20:22.606+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:20:22.606+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:20:22.609+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:20:22.608+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:20:22.610+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:20:22.626+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.031 seconds
[2025-06-19T01:20:53.036+0000] {processor.py:161} INFO - Started process (PID=51652) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:20:53.037+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:20:53.038+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:20:53.038+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:20:53.040+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:20:53.040+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:20:53.041+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:20:53.056+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.028 seconds
[2025-06-19T01:21:23.896+0000] {processor.py:161} INFO - Started process (PID=51688) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:21:23.897+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:21:23.898+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:21:23.898+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:21:23.901+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:21:23.901+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:21:23.902+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:21:23.919+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.033 seconds
[2025-06-19T01:21:54.508+0000] {processor.py:161} INFO - Started process (PID=51724) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:21:54.509+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:21:54.509+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:21:54.509+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:21:54.512+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:21:54.511+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:21:54.513+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:21:54.527+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.027 seconds
[2025-06-19T01:22:25.070+0000] {processor.py:161} INFO - Started process (PID=51760) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:22:25.071+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:22:25.072+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:22:25.072+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:22:25.075+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:22:25.074+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:22:25.075+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:22:25.092+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.028 seconds
[2025-06-19T01:22:55.846+0000] {processor.py:161} INFO - Started process (PID=51796) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:22:55.847+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:22:55.848+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:22:55.848+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:22:55.851+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:22:55.850+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:22:55.852+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:22:55.867+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.027 seconds
[2025-06-19T01:23:26.427+0000] {processor.py:161} INFO - Started process (PID=51832) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:23:26.428+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:23:26.429+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:23:26.429+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:23:26.432+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:23:26.431+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:23:26.433+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:23:26.446+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.026 seconds
[2025-06-19T01:23:57.118+0000] {processor.py:161} INFO - Started process (PID=51868) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:23:57.119+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:23:57.120+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:23:57.120+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:23:57.123+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:23:57.122+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:23:57.124+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:23:57.138+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.028 seconds
[2025-06-19T01:24:27.741+0000] {processor.py:161} INFO - Started process (PID=51904) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:24:27.742+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:24:27.743+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:24:27.743+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:24:27.746+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:24:27.745+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:24:27.747+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:24:27.761+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.028 seconds
[2025-06-19T01:24:58.208+0000] {processor.py:161} INFO - Started process (PID=51940) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:24:58.209+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:24:58.210+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:24:58.210+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:24:58.212+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:24:58.212+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:24:58.214+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:24:58.228+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.026 seconds
[2025-06-19T01:25:28.885+0000] {processor.py:161} INFO - Started process (PID=51976) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:25:28.886+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:25:28.888+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:25:28.887+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:25:28.890+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:25:28.890+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:25:28.891+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:25:28.908+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.030 seconds
[2025-06-19T01:25:59.475+0000] {processor.py:161} INFO - Started process (PID=52012) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:25:59.476+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:25:59.477+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:25:59.477+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:25:59.484+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:25:59.482+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:25:59.486+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:25:59.505+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.037 seconds
[2025-06-19T01:26:30.261+0000] {processor.py:161} INFO - Started process (PID=52048) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:26:30.262+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:26:30.263+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:26:30.263+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:26:30.266+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:26:30.265+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:26:30.267+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:26:30.284+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.034 seconds
[2025-06-19T01:27:00.701+0000] {processor.py:161} INFO - Started process (PID=52084) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:27:00.702+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:27:00.703+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:27:00.703+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:27:00.706+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:27:00.705+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:27:00.706+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:27:00.723+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.032 seconds
[2025-06-19T01:27:31.277+0000] {processor.py:161} INFO - Started process (PID=52120) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:27:31.278+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:27:31.280+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:27:31.279+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:27:31.283+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:27:31.282+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:27:31.284+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:27:31.302+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.036 seconds
[2025-06-19T01:28:01.918+0000] {processor.py:161} INFO - Started process (PID=52156) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:28:01.919+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:28:01.920+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:28:01.920+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:28:01.923+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:28:01.922+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:28:01.924+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:28:01.943+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.034 seconds
[2025-06-19T01:28:32.546+0000] {processor.py:161} INFO - Started process (PID=52192) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:28:32.547+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:28:32.548+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:28:32.548+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:28:32.551+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:28:32.550+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:28:32.552+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:28:32.570+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.032 seconds
[2025-06-19T01:29:03.419+0000] {processor.py:161} INFO - Started process (PID=52228) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:29:03.421+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:29:03.422+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:29:03.422+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:29:03.427+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:29:03.425+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:29:03.429+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:29:03.453+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.045 seconds
[2025-06-19T01:29:33.634+0000] {processor.py:161} INFO - Started process (PID=52264) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:29:33.635+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:29:33.636+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:29:33.636+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:29:33.640+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:29:33.639+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:29:33.641+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:29:33.667+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.046 seconds
[2025-06-19T01:30:03.826+0000] {processor.py:161} INFO - Started process (PID=52300) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:30:03.828+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:30:03.829+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:30:03.829+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:30:03.833+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:30:03.832+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:30:03.834+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:30:03.855+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.039 seconds
[2025-06-19T01:30:34.493+0000] {processor.py:161} INFO - Started process (PID=52336) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:30:34.494+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:30:34.495+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:30:34.494+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:30:34.498+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:30:34.497+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:30:34.499+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:30:34.516+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.032 seconds
[2025-06-19T01:31:04.971+0000] {processor.py:161} INFO - Started process (PID=52372) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:31:04.973+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:31:04.974+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:31:04.974+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:31:04.978+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:31:04.977+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:31:04.979+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:31:05.005+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.043 seconds
[2025-06-19T01:31:35.775+0000] {processor.py:161} INFO - Started process (PID=52408) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:31:35.776+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:31:35.777+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:31:35.777+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:31:35.781+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:31:35.780+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:31:35.783+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:31:35.805+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.040 seconds
[2025-06-19T01:32:06.402+0000] {processor.py:161} INFO - Started process (PID=52444) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:32:06.403+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:32:06.405+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:32:06.404+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:32:06.409+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:32:06.408+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:32:06.411+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:32:06.432+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.041 seconds
[2025-06-19T01:32:37.127+0000] {processor.py:161} INFO - Started process (PID=52480) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:32:37.129+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:32:37.130+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:32:37.130+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:32:37.134+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:32:37.133+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:32:37.135+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:32:37.158+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.040 seconds
[2025-06-19T01:33:07.819+0000] {processor.py:161} INFO - Started process (PID=52516) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:33:07.821+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:33:07.822+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:33:07.822+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:33:07.826+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:33:07.825+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:33:07.827+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:33:07.850+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.042 seconds
[2025-06-19T01:33:38.510+0000] {processor.py:161} INFO - Started process (PID=52552) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:33:38.511+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:33:38.512+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:33:38.512+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:33:38.515+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:33:38.514+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:33:38.516+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:33:38.539+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.039 seconds
[2025-06-19T01:34:09.188+0000] {processor.py:161} INFO - Started process (PID=52588) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:34:09.189+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:34:09.191+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:34:09.190+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:34:09.195+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:34:09.194+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:34:09.196+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:34:09.226+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.051 seconds
[2025-06-19T01:34:39.896+0000] {processor.py:161} INFO - Started process (PID=52624) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:34:39.898+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:34:39.899+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:34:39.899+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:34:39.904+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:34:39.903+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:34:39.905+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:34:39.926+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.040 seconds
[2025-06-19T01:35:10.651+0000] {processor.py:161} INFO - Started process (PID=52661) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:35:10.652+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:35:10.654+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:35:10.653+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:35:10.658+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:35:10.657+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:35:10.659+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:35:10.679+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.040 seconds
[2025-06-19T01:35:41.451+0000] {processor.py:161} INFO - Started process (PID=52697) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:35:41.453+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:35:41.454+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:35:41.454+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:35:41.459+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:35:41.458+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:35:41.460+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:35:41.483+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.042 seconds
[2025-06-19T01:36:12.358+0000] {processor.py:161} INFO - Started process (PID=52733) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:36:12.360+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:36:12.362+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:36:12.362+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:36:12.367+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:36:12.366+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:36:12.368+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:36:12.393+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.046 seconds
[2025-06-19T01:36:43.145+0000] {processor.py:161} INFO - Started process (PID=52769) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:36:43.146+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:36:43.147+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:36:43.147+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:36:43.152+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:36:43.150+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:36:43.153+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:36:43.176+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.041 seconds
[2025-06-19T01:37:13.618+0000] {processor.py:161} INFO - Started process (PID=52805) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:37:13.620+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:37:13.621+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:37:13.621+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:37:13.624+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:37:13.624+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:37:13.625+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:37:13.645+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.037 seconds
[2025-06-19T01:37:44.440+0000] {processor.py:161} INFO - Started process (PID=52841) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:37:44.442+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:37:44.444+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:37:44.444+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:37:44.449+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:37:44.448+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:37:44.450+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:37:44.473+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.045 seconds
[2025-06-19T01:38:15.183+0000] {processor.py:161} INFO - Started process (PID=52877) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:38:15.185+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:38:15.187+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:38:15.186+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:38:15.191+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:38:15.190+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:38:15.191+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:38:15.212+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.040 seconds
[2025-06-19T01:38:45.896+0000] {processor.py:161} INFO - Started process (PID=52914) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:38:45.898+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:38:45.899+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:38:45.899+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:38:45.903+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:38:45.902+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:38:45.905+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:38:45.925+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.038 seconds
[2025-06-19T01:39:16.515+0000] {processor.py:161} INFO - Started process (PID=52950) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:39:16.516+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:39:16.517+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:39:16.517+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:39:16.522+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:39:16.520+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:39:16.523+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:39:16.546+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.039 seconds
[2025-06-19T01:39:47.046+0000] {processor.py:161} INFO - Started process (PID=52986) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:39:47.048+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:39:47.049+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:39:47.049+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:39:47.053+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:39:47.052+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:39:47.054+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:39:47.075+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.038 seconds
[2025-06-19T01:40:17.699+0000] {processor.py:161} INFO - Started process (PID=53021) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:40:17.700+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:40:17.702+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:40:17.701+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:40:17.707+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:40:17.705+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:40:17.708+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:40:17.728+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.040 seconds
[2025-06-19T01:40:48.334+0000] {processor.py:161} INFO - Started process (PID=53057) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:40:48.335+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:40:48.336+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:40:48.336+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:40:48.339+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:40:48.338+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:40:48.340+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:40:48.360+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.036 seconds
[2025-06-19T01:41:19.100+0000] {processor.py:161} INFO - Started process (PID=53094) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:41:19.101+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:41:19.103+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:41:19.102+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:41:19.107+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:41:19.106+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:41:19.108+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:41:19.131+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.041 seconds
[2025-06-19T01:41:49.890+0000] {processor.py:161} INFO - Started process (PID=53130) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:41:49.892+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:41:49.893+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:41:49.893+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:41:49.896+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:41:49.895+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:41:49.898+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:41:49.922+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.042 seconds
[2025-06-19T01:42:21.008+0000] {processor.py:161} INFO - Started process (PID=53167) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:42:21.009+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:42:21.011+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:42:21.010+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:42:21.015+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:42:21.013+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:42:21.016+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:42:21.042+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.045 seconds
[2025-06-19T01:42:53.054+0000] {processor.py:161} INFO - Started process (PID=53209) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:42:53.056+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:42:53.057+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:42:53.057+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:42:53.061+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:42:53.060+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:42:53.062+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:42:53.086+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.044 seconds
[2025-06-19T01:43:23.689+0000] {processor.py:161} INFO - Started process (PID=53245) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:43:23.690+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:43:23.691+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:43:23.691+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:43:23.697+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:43:23.695+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:43:23.699+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:43:23.722+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.044 seconds
[2025-06-19T01:43:53.872+0000] {processor.py:161} INFO - Started process (PID=53281) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:43:53.873+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:43:53.875+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:43:53.874+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:43:53.879+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:43:53.878+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:43:53.881+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:43:53.906+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.048 seconds
[2025-06-19T01:44:24.074+0000] {processor.py:161} INFO - Started process (PID=53317) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:44:24.076+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:44:24.077+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:44:24.077+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:44:24.082+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:44:24.080+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:44:24.083+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:44:24.110+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.052 seconds
[2025-06-19T01:44:54.526+0000] {processor.py:161} INFO - Started process (PID=53354) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:44:54.528+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:44:54.530+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:44:54.529+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:44:54.535+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:44:54.533+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:44:54.536+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:44:54.559+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.045 seconds
[2025-06-19T01:45:24.820+0000] {processor.py:161} INFO - Started process (PID=53390) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:45:24.822+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:45:24.823+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:45:24.823+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:45:24.830+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:45:24.827+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:45:24.832+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:45:24.857+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.050 seconds
[2025-06-19T01:45:55.636+0000] {processor.py:161} INFO - Started process (PID=53426) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:45:55.638+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:45:55.640+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:45:55.639+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:45:55.647+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:45:55.645+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:45:55.649+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:45:55.687+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.067 seconds
[2025-06-19T01:46:26.334+0000] {processor.py:161} INFO - Started process (PID=53462) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:46:26.335+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:46:26.337+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:46:26.336+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:46:26.344+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:46:26.342+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:46:26.346+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:46:26.379+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.062 seconds
[2025-06-19T01:46:56.478+0000] {processor.py:161} INFO - Started process (PID=53498) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:46:56.479+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:46:56.482+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:46:56.481+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:46:56.486+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:46:56.485+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:46:56.488+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:46:56.513+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.046 seconds
[2025-06-19T01:47:27.140+0000] {processor.py:161} INFO - Started process (PID=53534) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:47:27.142+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:47:27.143+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:47:27.143+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:47:27.149+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:47:27.147+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:47:27.150+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:47:27.178+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.050 seconds
[2025-06-19T01:47:57.403+0000] {processor.py:161} INFO - Started process (PID=53570) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:47:57.404+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:47:57.406+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:47:57.406+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:47:57.414+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:47:57.412+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:47:57.415+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:47:57.443+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.055 seconds
[2025-06-19T01:48:27.778+0000] {processor.py:161} INFO - Started process (PID=53606) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:48:27.780+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:48:27.781+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:48:27.781+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:48:27.786+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:48:27.785+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:48:27.787+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:48:27.815+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.050 seconds
[2025-06-19T01:48:58.063+0000] {processor.py:161} INFO - Started process (PID=53642) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:48:58.064+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:48:58.066+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:48:58.065+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:48:58.069+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:48:58.068+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:48:58.071+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:48:58.097+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.046 seconds
[2025-06-19T01:49:28.534+0000] {processor.py:161} INFO - Started process (PID=53678) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:49:28.536+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:49:28.538+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:49:28.537+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:49:28.543+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:49:28.541+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:49:28.546+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:49:28.576+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.059 seconds
[2025-06-19T01:49:58.694+0000] {processor.py:161} INFO - Started process (PID=53714) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:49:58.695+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:49:58.697+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:49:58.696+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:49:58.702+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:49:58.700+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:49:58.702+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:49:58.727+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.045 seconds
[2025-06-19T01:50:29.179+0000] {processor.py:161} INFO - Started process (PID=53750) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:50:29.182+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:50:29.185+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:50:29.184+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:50:29.192+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:50:29.190+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:50:29.193+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:50:29.222+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.061 seconds
[2025-06-19T01:50:59.322+0000] {processor.py:161} INFO - Started process (PID=53786) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:50:59.324+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:50:59.325+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:50:59.325+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:50:59.329+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:50:59.328+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:50:59.330+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:50:59.350+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.039 seconds
[2025-06-19T01:51:29.965+0000] {processor.py:161} INFO - Started process (PID=53823) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:51:29.967+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:51:29.970+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:51:29.969+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:51:29.975+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:51:29.974+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:51:29.976+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:51:30.001+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.047 seconds
[2025-06-19T01:52:00.700+0000] {processor.py:161} INFO - Started process (PID=53859) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:52:00.702+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:52:00.703+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:52:00.703+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:52:00.708+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:52:00.707+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:52:00.710+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:52:00.739+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.053 seconds
[2025-06-19T01:52:32.111+0000] {processor.py:161} INFO - Started process (PID=53895) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:52:32.112+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:52:32.113+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:52:32.113+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:52:32.118+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:52:32.116+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:52:32.120+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:52:32.140+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.043 seconds
[2025-06-19T01:53:02.554+0000] {processor.py:161} INFO - Started process (PID=53931) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:53:02.555+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:53:02.556+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:53:02.556+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:53:02.560+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:53:02.559+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:53:02.561+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:53:02.581+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.038 seconds
[2025-06-19T01:53:32.806+0000] {processor.py:161} INFO - Started process (PID=53967) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:53:32.807+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:53:32.808+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:53:32.807+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:53:32.811+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:53:32.810+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:53:32.812+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:53:32.831+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.035 seconds
[2025-06-19T01:54:03.135+0000] {processor.py:161} INFO - Started process (PID=54004) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:54:03.136+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:54:03.138+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:54:03.137+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:54:03.142+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:54:03.141+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:54:03.143+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:54:03.169+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.042 seconds
[2025-06-19T01:54:33.528+0000] {processor.py:161} INFO - Started process (PID=54040) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:54:33.529+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:54:33.531+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:54:33.530+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:54:33.535+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:54:33.534+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:54:33.536+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:54:33.561+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.043 seconds
[2025-06-19T01:55:03.948+0000] {processor.py:161} INFO - Started process (PID=54076) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:55:03.950+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:55:03.952+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:55:03.951+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:55:03.961+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:55:03.959+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:55:03.962+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:55:03.981+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.043 seconds
[2025-06-19T01:55:34.152+0000] {processor.py:161} INFO - Started process (PID=54112) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:55:34.153+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:55:34.154+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:55:34.154+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:55:34.158+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:55:34.157+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:55:34.159+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:55:34.180+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.038 seconds
[2025-06-19T01:56:04.471+0000] {processor.py:161} INFO - Started process (PID=54148) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:56:04.472+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:56:04.474+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:56:04.473+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:56:04.477+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:56:04.476+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:56:04.478+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:56:04.497+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.035 seconds
[2025-06-19T01:56:34.770+0000] {processor.py:161} INFO - Started process (PID=54184) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:56:34.772+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:56:34.773+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:56:34.773+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:56:34.777+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:56:34.776+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:56:34.779+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:56:34.798+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.038 seconds
[2025-06-19T01:57:05.067+0000] {processor.py:161} INFO - Started process (PID=54220) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:57:05.069+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:57:05.070+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:57:05.070+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:57:05.073+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:57:05.072+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:57:05.074+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:57:05.093+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.035 seconds
[2025-06-19T01:57:35.615+0000] {processor.py:161} INFO - Started process (PID=54256) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:57:35.616+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:57:35.618+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:57:35.617+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:57:35.622+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:57:35.621+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:57:35.623+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:57:35.642+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.037 seconds
[2025-06-19T01:58:05.967+0000] {processor.py:161} INFO - Started process (PID=54292) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:58:05.968+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:58:05.970+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:58:05.969+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:58:05.974+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:58:05.973+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:58:05.975+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:58:05.999+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.043 seconds
[2025-06-19T01:58:36.344+0000] {processor.py:161} INFO - Started process (PID=54328) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:58:36.345+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:58:36.347+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:58:36.346+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:58:36.351+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:58:36.350+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:58:36.352+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:58:36.372+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.037 seconds
[2025-06-19T01:59:06.666+0000] {processor.py:161} INFO - Started process (PID=54364) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:59:06.668+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:59:06.669+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:59:06.669+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:59:06.673+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:59:06.672+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:59:06.674+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:59:06.695+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.040 seconds
[2025-06-19T01:59:37.144+0000] {processor.py:161} INFO - Started process (PID=54400) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:59:37.146+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T01:59:37.147+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:59:37.147+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:59:37.151+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:59:37.149+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:59:37.152+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T01:59:37.172+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.038 seconds
[2025-06-19T02:00:07.545+0000] {processor.py:161} INFO - Started process (PID=54436) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T02:00:07.546+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T02:00:07.547+0000] {logging_mixin.py:188} INFO - [2025-06-19T02:00:07.547+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T02:00:07.550+0000] {logging_mixin.py:188} INFO - [2025-06-19T02:00:07.549+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T02:00:07.551+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T02:00:07.571+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.035 seconds
[2025-06-19T02:00:37.716+0000] {processor.py:161} INFO - Started process (PID=54472) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T02:00:37.717+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py for tasks to queue
[2025-06-19T02:00:37.719+0000] {logging_mixin.py:188} INFO - [2025-06-19T02:00:37.718+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T02:00:37.722+0000] {logging_mixin.py:188} INFO - [2025-06-19T02:00:37.721+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py", line 27, in <module>
    from airflow.providers.standard.operators.datetime import BranchDateTimeOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T02:00:37.723+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py
[2025-06-19T02:00:37.745+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_branch_datetime_operator.py took 0.040 seconds
