[2025-06-19T01:17:19.037+0000] {processor.py:161} INFO - Started process (PID=51390) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:17:19.039+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:17:19.040+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:17:19.039+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:17:19.042+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:17:19.041+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:17:19.043+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:17:19.062+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.034 seconds
[2025-06-19T01:17:49.573+0000] {processor.py:161} INFO - Started process (PID=51426) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:17:49.574+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:17:49.575+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:17:49.575+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:17:49.578+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:17:49.577+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:17:49.578+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:17:49.591+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.027 seconds
[2025-06-19T01:18:20.067+0000] {processor.py:161} INFO - Started process (PID=51462) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:18:20.068+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:18:20.069+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:18:20.068+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:18:20.071+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:18:20.070+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:18:20.072+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:18:20.086+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.028 seconds
[2025-06-19T01:18:50.718+0000] {processor.py:161} INFO - Started process (PID=51498) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:18:50.719+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:18:50.721+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:18:50.720+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:18:50.723+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:18:50.722+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:18:50.724+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:18:50.746+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.037 seconds
[2025-06-19T01:19:21.436+0000] {processor.py:161} INFO - Started process (PID=51540) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:19:21.437+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:19:21.438+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:19:21.438+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:19:21.442+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:19:21.441+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:19:21.442+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:19:21.458+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.035 seconds
[2025-06-19T01:19:52.026+0000] {processor.py:161} INFO - Started process (PID=51576) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:19:52.028+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:19:52.029+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:19:52.028+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:19:52.032+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:19:52.031+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:19:52.033+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:19:52.050+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.031 seconds
[2025-06-19T01:20:22.447+0000] {processor.py:161} INFO - Started process (PID=51612) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:20:22.448+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:20:22.449+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:20:22.449+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:20:22.452+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:20:22.451+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:20:22.453+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:20:22.467+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.026 seconds
[2025-06-19T01:20:52.911+0000] {processor.py:161} INFO - Started process (PID=51648) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:20:52.912+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:20:52.913+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:20:52.913+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:20:52.916+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:20:52.915+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:20:52.917+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:20:52.931+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.027 seconds
[2025-06-19T01:21:23.605+0000] {processor.py:161} INFO - Started process (PID=51684) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:21:23.607+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:21:23.609+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:21:23.609+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:21:23.612+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:21:23.611+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:21:23.613+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:21:23.633+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.042 seconds
[2025-06-19T01:21:54.386+0000] {processor.py:161} INFO - Started process (PID=51720) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:21:54.387+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:21:54.388+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:21:54.388+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:21:54.391+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:21:54.390+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:21:54.391+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:21:54.406+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.028 seconds
[2025-06-19T01:22:24.865+0000] {processor.py:161} INFO - Started process (PID=51756) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:22:24.867+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:22:24.868+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:22:24.867+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:22:24.870+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:22:24.870+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:22:24.871+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:22:24.885+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.028 seconds
[2025-06-19T01:22:55.594+0000] {processor.py:161} INFO - Started process (PID=51792) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:22:55.595+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:22:55.597+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:22:55.597+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:22:55.600+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:22:55.599+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:22:55.601+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:22:55.617+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.033 seconds
[2025-06-19T01:23:26.301+0000] {processor.py:161} INFO - Started process (PID=51828) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:23:26.302+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:23:26.303+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:23:26.303+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:23:26.305+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:23:26.305+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:23:26.308+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:23:26.325+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.031 seconds
[2025-06-19T01:23:56.896+0000] {processor.py:161} INFO - Started process (PID=51864) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:23:56.897+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:23:56.898+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:23:56.898+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:23:56.901+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:23:56.900+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:23:56.902+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:23:56.917+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.027 seconds
[2025-06-19T01:24:27.599+0000] {processor.py:161} INFO - Started process (PID=51900) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:24:27.601+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:24:27.601+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:24:27.601+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:24:27.604+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:24:27.603+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:24:27.604+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:24:27.619+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.027 seconds
[2025-06-19T01:24:58.073+0000] {processor.py:161} INFO - Started process (PID=51936) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:24:58.074+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:24:58.075+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:24:58.075+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:24:58.077+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:24:58.077+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:24:58.078+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:24:58.092+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.025 seconds
[2025-06-19T01:25:28.674+0000] {processor.py:161} INFO - Started process (PID=51972) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:25:28.675+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:25:28.676+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:25:28.676+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:25:28.680+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:25:28.679+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:25:28.681+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:25:28.695+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.029 seconds
[2025-06-19T01:25:59.255+0000] {processor.py:161} INFO - Started process (PID=52008) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:25:59.256+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:25:59.258+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:25:59.257+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:25:59.261+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:25:59.260+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:25:59.262+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:25:59.282+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.037 seconds
[2025-06-19T01:26:30.106+0000] {processor.py:161} INFO - Started process (PID=52044) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:26:30.107+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:26:30.108+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:26:30.108+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:26:30.111+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:26:30.111+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:26:30.112+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:26:30.129+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.032 seconds
[2025-06-19T01:27:00.567+0000] {processor.py:161} INFO - Started process (PID=52080) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:27:00.568+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:27:00.569+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:27:00.569+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:27:00.572+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:27:00.571+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:27:00.573+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:27:00.590+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.032 seconds
[2025-06-19T01:27:31.145+0000] {processor.py:161} INFO - Started process (PID=52116) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:27:31.146+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:27:31.147+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:27:31.146+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:27:31.150+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:27:31.149+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:27:31.150+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:27:31.166+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.030 seconds
[2025-06-19T01:28:01.672+0000] {processor.py:161} INFO - Started process (PID=52152) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:28:01.673+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:28:01.674+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:28:01.674+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:28:01.678+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:28:01.677+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:28:01.679+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:28:01.697+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.035 seconds
[2025-06-19T01:28:32.398+0000] {processor.py:161} INFO - Started process (PID=52188) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:28:32.399+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:28:32.400+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:28:32.400+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:28:32.403+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:28:32.402+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:28:32.404+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:28:32.422+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.032 seconds
[2025-06-19T01:29:03.234+0000] {processor.py:161} INFO - Started process (PID=52224) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:29:03.236+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:29:03.237+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:29:03.237+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:29:03.242+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:29:03.240+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:29:03.243+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:29:03.271+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.050 seconds
[2025-06-19T01:29:33.370+0000] {processor.py:161} INFO - Started process (PID=52260) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:29:33.371+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:29:33.373+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:29:33.372+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:29:33.377+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:29:33.376+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:29:33.378+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:29:33.399+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.041 seconds
[2025-06-19T01:30:03.571+0000] {processor.py:161} INFO - Started process (PID=52296) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:30:03.572+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:30:03.574+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:30:03.573+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:30:03.578+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:30:03.577+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:30:03.579+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:30:03.600+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.039 seconds
[2025-06-19T01:30:34.263+0000] {processor.py:161} INFO - Started process (PID=52332) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:30:34.265+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:30:34.266+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:30:34.265+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:30:34.269+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:30:34.268+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:30:34.270+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:30:34.288+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.033 seconds
[2025-06-19T01:31:04.807+0000] {processor.py:161} INFO - Started process (PID=52368) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:31:04.808+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:31:04.810+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:31:04.809+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:31:04.814+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:31:04.813+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:31:04.814+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:31:04.835+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.036 seconds
[2025-06-19T01:31:35.502+0000] {processor.py:161} INFO - Started process (PID=52404) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:31:35.503+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:31:35.504+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:31:35.503+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:31:35.507+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:31:35.506+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:31:35.509+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:31:35.532+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.039 seconds
[2025-06-19T01:32:06.152+0000] {processor.py:161} INFO - Started process (PID=52440) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:32:06.154+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:32:06.155+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:32:06.154+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:32:06.160+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:32:06.158+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:32:06.161+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:32:06.183+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.044 seconds
[2025-06-19T01:32:36.882+0000] {processor.py:161} INFO - Started process (PID=52476) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:32:36.883+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:32:36.885+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:32:36.884+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:32:36.889+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:32:36.888+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:32:36.890+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:32:36.910+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.038 seconds
[2025-06-19T01:33:07.576+0000] {processor.py:161} INFO - Started process (PID=52512) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:33:07.577+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:33:07.578+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:33:07.578+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:33:07.581+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:33:07.580+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:33:07.582+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:33:07.601+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.035 seconds
[2025-06-19T01:33:38.273+0000] {processor.py:161} INFO - Started process (PID=52548) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:33:38.274+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:33:38.276+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:33:38.276+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:33:38.280+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:33:38.280+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:33:38.281+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:33:38.301+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.038 seconds
[2025-06-19T01:34:08.994+0000] {processor.py:161} INFO - Started process (PID=52584) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:34:08.996+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:34:08.997+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:34:08.997+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:34:09.001+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:34:09.000+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:34:09.002+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:34:09.025+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.043 seconds
[2025-06-19T01:34:39.730+0000] {processor.py:161} INFO - Started process (PID=52620) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:34:39.731+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:34:39.732+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:34:39.732+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:34:39.736+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:34:39.735+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:34:39.737+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:34:39.758+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.039 seconds
[2025-06-19T01:35:10.409+0000] {processor.py:161} INFO - Started process (PID=52657) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:35:10.411+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:35:10.412+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:35:10.412+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:35:10.416+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:35:10.415+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:35:10.417+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:35:10.436+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.039 seconds
[2025-06-19T01:35:41.271+0000] {processor.py:161} INFO - Started process (PID=52693) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:35:41.272+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:35:41.274+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:35:41.273+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:35:41.279+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:35:41.278+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:35:41.280+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:35:41.305+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.044 seconds
[2025-06-19T01:36:12.071+0000] {processor.py:161} INFO - Started process (PID=52729) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:36:12.073+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:36:12.075+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:36:12.074+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:36:12.079+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:36:12.078+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:36:12.081+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:36:12.107+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.047 seconds
[2025-06-19T01:36:42.892+0000] {processor.py:161} INFO - Started process (PID=52765) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:36:42.893+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:36:42.894+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:36:42.894+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:36:42.898+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:36:42.897+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:36:42.899+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:36:42.921+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.040 seconds
[2025-06-19T01:37:13.440+0000] {processor.py:161} INFO - Started process (PID=52801) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:37:13.441+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:37:13.443+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:37:13.442+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:37:13.447+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:37:13.446+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:37:13.448+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:37:13.481+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.050 seconds
[2025-06-19T01:37:44.251+0000] {processor.py:161} INFO - Started process (PID=52837) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:37:44.252+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:37:44.254+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:37:44.253+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:37:44.259+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:37:44.258+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:37:44.261+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:37:44.283+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.043 seconds
[2025-06-19T01:38:15.014+0000] {processor.py:161} INFO - Started process (PID=52873) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:38:15.015+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:38:15.017+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:38:15.016+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:38:15.020+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:38:15.019+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:38:15.021+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:38:15.048+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.045 seconds
[2025-06-19T01:38:45.635+0000] {processor.py:161} INFO - Started process (PID=52910) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:38:45.637+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:38:45.638+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:38:45.638+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:38:45.641+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:38:45.641+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:38:45.642+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:38:45.668+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.044 seconds
[2025-06-19T01:39:16.282+0000] {processor.py:161} INFO - Started process (PID=52946) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:39:16.283+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:39:16.285+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:39:16.284+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:39:16.289+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:39:16.288+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:39:16.290+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:39:16.309+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.037 seconds
[2025-06-19T01:39:46.883+0000] {processor.py:161} INFO - Started process (PID=52982) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:39:46.885+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:39:46.886+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:39:46.886+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:39:46.890+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:39:46.889+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:39:46.891+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:39:46.911+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.038 seconds
[2025-06-19T01:40:17.612+0000] {processor.py:161} INFO - Started process (PID=53018) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:40:17.614+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:40:17.615+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:40:17.615+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:40:17.619+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:40:17.618+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:40:17.620+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:40:17.642+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.041 seconds
[2025-06-19T01:40:48.166+0000] {processor.py:161} INFO - Started process (PID=53054) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:40:48.167+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:40:48.168+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:40:48.168+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:40:48.171+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:40:48.170+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:40:48.172+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:40:48.201+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.046 seconds
[2025-06-19T01:41:18.915+0000] {processor.py:161} INFO - Started process (PID=53090) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:41:18.916+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:41:18.917+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:41:18.917+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:41:18.921+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:41:18.920+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:41:18.923+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:41:18.945+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.041 seconds
[2025-06-19T01:41:49.714+0000] {processor.py:161} INFO - Started process (PID=53126) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:41:49.716+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:41:49.717+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:41:49.717+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:41:49.720+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:41:49.720+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:41:49.722+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:41:49.745+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.041 seconds
[2025-06-19T01:42:20.725+0000] {processor.py:161} INFO - Started process (PID=53163) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:42:20.727+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:42:20.728+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:42:20.728+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:42:20.732+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:42:20.731+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:42:20.734+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:42:20.762+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.050 seconds
[2025-06-19T01:42:52.651+0000] {processor.py:161} INFO - Started process (PID=53199) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:42:52.667+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:42:52.675+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:42:52.674+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:42:52.681+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:42:52.680+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:42:52.685+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:42:52.712+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.072 seconds
[2025-06-19T01:43:23.478+0000] {processor.py:161} INFO - Started process (PID=53241) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:43:23.480+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:43:23.482+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:43:23.481+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:43:23.486+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:43:23.485+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:43:23.488+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:43:23.517+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.051 seconds
[2025-06-19T01:43:53.671+0000] {processor.py:161} INFO - Started process (PID=53277) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:43:53.672+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:43:53.674+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:43:53.673+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:43:53.677+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:43:53.676+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:43:53.678+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:43:53.704+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.044 seconds
[2025-06-19T01:44:23.811+0000] {processor.py:161} INFO - Started process (PID=53313) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:44:23.813+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:44:23.815+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:44:23.814+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:44:23.819+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:44:23.818+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:44:23.820+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:44:23.844+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.042 seconds
[2025-06-19T01:44:54.230+0000] {processor.py:161} INFO - Started process (PID=53350) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:44:54.231+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:44:54.233+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:44:54.233+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:44:54.238+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:44:54.237+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:44:54.239+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:44:54.269+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.054 seconds
[2025-06-19T01:45:24.609+0000] {processor.py:161} INFO - Started process (PID=53386) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:45:24.610+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:45:24.612+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:45:24.612+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:45:24.617+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:45:24.615+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:45:24.619+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:45:24.643+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.046 seconds
[2025-06-19T01:45:55.236+0000] {processor.py:161} INFO - Started process (PID=53422) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:45:55.238+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:45:55.240+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:45:55.240+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:45:55.245+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:45:55.244+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:45:55.247+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:45:55.281+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.061 seconds
[2025-06-19T01:46:25.936+0000] {processor.py:161} INFO - Started process (PID=53458) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:46:25.938+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:46:25.941+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:46:25.940+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:46:25.946+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:46:25.944+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:46:25.948+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:46:25.985+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.066 seconds
[2025-06-19T01:46:56.152+0000] {processor.py:161} INFO - Started process (PID=53494) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:46:56.154+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:46:56.155+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:46:56.155+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:46:56.159+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:46:56.158+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:46:56.160+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:46:56.186+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.046 seconds
[2025-06-19T01:47:26.820+0000] {processor.py:161} INFO - Started process (PID=53530) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:47:26.822+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:47:26.823+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:47:26.823+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:47:26.829+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:47:26.827+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:47:26.830+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:47:26.861+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.056 seconds
[2025-06-19T01:47:57.058+0000] {processor.py:161} INFO - Started process (PID=53566) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:47:57.060+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:47:57.063+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:47:57.062+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:47:57.068+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:47:57.067+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:47:57.069+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:47:57.099+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.054 seconds
[2025-06-19T01:48:27.452+0000] {processor.py:161} INFO - Started process (PID=53602) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:48:27.454+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:48:27.455+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:48:27.455+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:48:27.459+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:48:27.458+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:48:27.461+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:48:27.488+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.048 seconds
[2025-06-19T01:48:57.871+0000] {processor.py:161} INFO - Started process (PID=53638) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:48:57.872+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:48:57.874+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:48:57.873+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:48:57.878+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:48:57.877+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:48:57.879+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:48:57.903+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.043 seconds
[2025-06-19T01:49:28.278+0000] {processor.py:161} INFO - Started process (PID=53674) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:49:28.281+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:49:28.284+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:49:28.283+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:49:28.290+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:49:28.288+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:49:28.291+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:49:28.326+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.062 seconds
[2025-06-19T01:49:58.493+0000] {processor.py:161} INFO - Started process (PID=53711) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:49:58.495+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:49:58.497+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:49:58.496+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:49:58.502+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:49:58.501+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:49:58.503+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:49:58.529+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.047 seconds
[2025-06-19T01:50:28.910+0000] {processor.py:161} INFO - Started process (PID=53747) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:50:28.912+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:50:28.914+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:50:28.914+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:50:28.920+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:50:28.919+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:50:28.922+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:50:28.954+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.058 seconds
[2025-06-19T01:50:59.065+0000] {processor.py:161} INFO - Started process (PID=53783) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:50:59.067+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:50:59.068+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:50:59.068+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:50:59.072+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:50:59.071+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:50:59.073+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:50:59.096+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.045 seconds
[2025-06-19T01:51:29.666+0000] {processor.py:161} INFO - Started process (PID=53819) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:51:29.668+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:51:29.669+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:51:29.669+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:51:29.673+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:51:29.672+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:51:29.674+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:51:29.699+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.045 seconds
[2025-06-19T01:52:00.351+0000] {processor.py:161} INFO - Started process (PID=53855) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:52:00.353+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:52:00.355+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:52:00.354+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:52:00.360+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:52:00.359+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:52:00.361+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:52:00.389+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.055 seconds
[2025-06-19T01:52:31.905+0000] {processor.py:161} INFO - Started process (PID=53891) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:52:31.906+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:52:31.908+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:52:31.908+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:52:31.913+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:52:31.911+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:52:31.914+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:52:31.943+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.048 seconds
[2025-06-19T01:53:02.372+0000] {processor.py:161} INFO - Started process (PID=53927) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:53:02.373+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:53:02.375+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:53:02.374+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:53:02.381+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:53:02.377+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:53:02.382+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:53:02.406+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.044 seconds
[2025-06-19T01:53:32.653+0000] {processor.py:161} INFO - Started process (PID=53963) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:53:32.654+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:53:32.656+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:53:32.655+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:53:32.659+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:53:32.658+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:53:32.660+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:53:32.680+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.036 seconds
[2025-06-19T01:54:02.895+0000] {processor.py:161} INFO - Started process (PID=54000) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:54:02.896+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:54:02.897+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:54:02.897+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:54:02.901+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:54:02.900+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:54:02.902+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:54:02.921+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.035 seconds
[2025-06-19T01:54:33.286+0000] {processor.py:161} INFO - Started process (PID=54036) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:54:33.287+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:54:33.288+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:54:33.288+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:54:33.291+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:54:33.290+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:54:33.293+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:54:33.313+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.037 seconds
[2025-06-19T01:55:03.660+0000] {processor.py:161} INFO - Started process (PID=54072) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:55:03.661+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:55:03.662+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:55:03.662+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:55:03.666+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:55:03.665+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:55:03.668+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:55:03.688+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.038 seconds
[2025-06-19T01:55:33.993+0000] {processor.py:161} INFO - Started process (PID=54108) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:55:33.994+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:55:33.995+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:55:33.995+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:55:33.998+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:55:33.997+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:55:33.999+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:55:34.019+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.036 seconds
[2025-06-19T01:56:04.275+0000] {processor.py:161} INFO - Started process (PID=54144) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:56:04.276+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:56:04.277+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:56:04.277+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:56:04.281+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:56:04.280+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:56:04.282+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:56:04.303+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.037 seconds
[2025-06-19T01:56:34.605+0000] {processor.py:161} INFO - Started process (PID=54180) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:56:34.607+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:56:34.608+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:56:34.608+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:56:34.611+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:56:34.610+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:56:34.612+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:56:34.631+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.035 seconds
[2025-06-19T01:57:04.902+0000] {processor.py:161} INFO - Started process (PID=54216) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:57:04.903+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:57:04.905+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:57:04.904+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:57:04.908+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:57:04.907+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:57:04.909+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:57:04.928+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.034 seconds
[2025-06-19T01:57:35.345+0000] {processor.py:161} INFO - Started process (PID=54252) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:57:35.346+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:57:35.347+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:57:35.347+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:57:35.350+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:57:35.349+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:57:35.351+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:57:35.371+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.035 seconds
[2025-06-19T01:58:05.796+0000] {processor.py:161} INFO - Started process (PID=54288) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:58:05.798+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:58:05.799+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:58:05.798+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:58:05.803+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:58:05.802+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:58:05.804+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:58:05.825+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.038 seconds
[2025-06-19T01:58:36.173+0000] {processor.py:161} INFO - Started process (PID=54324) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:58:36.175+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:58:36.176+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:58:36.176+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:58:36.180+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:58:36.179+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:58:36.184+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:58:36.203+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.040 seconds
[2025-06-19T01:59:06.509+0000] {processor.py:161} INFO - Started process (PID=54360) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:59:06.510+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:59:06.511+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:59:06.511+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:59:06.515+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:59:06.514+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:59:06.515+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:59:06.534+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.035 seconds
[2025-06-19T01:59:36.987+0000] {processor.py:161} INFO - Started process (PID=54396) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:59:36.989+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T01:59:36.990+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:59:36.990+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:59:36.993+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:59:36.993+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:59:36.994+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T01:59:37.014+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.035 seconds
[2025-06-19T02:00:07.292+0000] {processor.py:161} INFO - Started process (PID=54432) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T02:00:07.294+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T02:00:07.297+0000] {logging_mixin.py:188} INFO - [2025-06-19T02:00:07.296+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T02:00:07.304+0000] {logging_mixin.py:188} INFO - [2025-06-19T02:00:07.303+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T02:00:07.305+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T02:00:07.327+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.044 seconds
[2025-06-19T02:00:37.543+0000] {processor.py:161} INFO - Started process (PID=54468) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T02:00:37.544+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py for tasks to queue
[2025-06-19T02:00:37.545+0000] {logging_mixin.py:188} INFO - [2025-06-19T02:00:37.544+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T02:00:37.547+0000] {logging_mixin.py:188} INFO - [2025-06-19T02:00:37.546+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py", line 45, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T02:00:37.548+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py
[2025-06-19T02:00:37.563+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_external_task_marker_dag.py took 0.028 seconds
