[2025-06-18T17:34:44.130+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-18T17:34:44.155+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecommerce_daily_etl.process_and_load_to_snowflake manual__2025-06-18T17:34:42.725077+00:00 [queued]>
[2025-06-18T17:34:44.160+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecommerce_daily_etl.process_and_load_to_snowflake manual__2025-06-18T17:34:42.725077+00:00 [queued]>
[2025-06-18T17:34:44.161+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-06-18T17:34:44.171+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): process_and_load_to_snowflake> on 2025-06-18 17:34:42.725077+00:00
[2025-06-18T17:34:44.178+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2365) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-18T17:34:44.180+0000] {standard_task_runner.py:63} INFO - Started process 2367 to run task
[2025-06-18T17:34:44.180+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ecommerce_daily_etl', 'process_and_load_to_snowflake', 'manual__2025-06-18T17:34:42.725077+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/ecommerce_daily_etl.py.py', '--cfg-path', '/tmp/tmpd8pdjocx']
[2025-06-18T17:34:44.182+0000] {standard_task_runner.py:91} INFO - Job 6: Subtask process_and_load_to_snowflake
[2025-06-18T17:34:44.222+0000] {task_command.py:426} INFO - Running <TaskInstance: ecommerce_daily_etl.process_and_load_to_snowflake manual__2025-06-18T17:34:42.725077+00:00 [running]> on host fbc1e8976316
[2025-06-18T17:34:44.279+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ecommerce_daily_etl' AIRFLOW_CTX_TASK_ID='process_and_load_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2025-06-18T17:34:42.725077+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-18T17:34:42.725077+00:00'
[2025-06-18T17:34:44.280+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-18T17:34:44.288+0000] {base.py:84} INFO - Using connection ID 'snowflake_default' for task execution.
[2025-06-18T17:34:44.290+0000] {spark_submit.py:340} INFO - Spark-Submit cmd: spark-submit --master  --packages net.snowflake:snowflake-jdbc:3.14.4,net.snowflake:spark-snowflake_2.12:2.12.0-spark_3.5,org.apache.hadoop:hadoop-aws:3.3.6,com.amazonaws:aws-java-sdk-bundle:1.12.262 --name arrow-spark /opt/***/dags/spark_scripts/process_daily_events.py --s3_input_path s3a://kafka-cust-transactions/raw/user_events/ --snowflake_table ECOMMERCE_DB.ANALYTICS.CUSTOMER_360_PROFILE
[2025-06-18T17:34:44.399+0000] {spark_submit.py:491} INFO - /home/***/.local/lib/python3.12/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-06-18T17:34:44.400+0000] {spark_submit.py:491} INFO - JAVA_HOME is not set
[2025-06-18T17:34:44.401+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-18T17:34:44.408+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 156, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 422, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master  --packages net.snowflake:snowflake-jdbc:3.14.4,net.snowflake:spark-snowflake_2.12:2.12.0-spark_3.5,org.apache.hadoop:hadoop-aws:3.3.6,com.amazonaws:aws-java-sdk-bundle:1.12.262 --name arrow-spark /opt/***/dags/spark_scripts/process_daily_events.py --s3_input_path s3a://kafka-cust-transactions/raw/user_events/ --snowflake_table ECOMMERCE_DB.ANALYTICS.CUSTOMER_360_PROFILE. Error code is: 1.
[2025-06-18T17:34:44.412+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=ecommerce_daily_etl, task_id=process_and_load_to_snowflake, run_id=manual__2025-06-18T17:34:42.725077+00:00, execution_date=20250618T173442, start_date=20250618T173444, end_date=20250618T173444
[2025-06-18T17:34:44.421+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 6 for task process_and_load_to_snowflake (Cannot execute: spark-submit --master  --packages net.snowflake:snowflake-jdbc:3.14.4,net.snowflake:spark-snowflake_2.12:2.12.0-spark_3.5,org.apache.hadoop:hadoop-aws:3.3.6,com.amazonaws:aws-java-sdk-bundle:1.12.262 --name arrow-spark /opt/***/dags/spark_scripts/process_daily_events.py --s3_input_path s3a://kafka-cust-transactions/raw/user_events/ --snowflake_table ECOMMERCE_DB.ANALYTICS.CUSTOMER_360_PROFILE. Error code is: 1.; 2367)
[2025-06-18T17:34:44.434+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-18T17:34:44.446+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-18T17:34:44.448+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
