[2025-06-18T15:48:29.947+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-18T15:48:29.963+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecommerce_daily_etl.process_and_load_to_snowflake scheduled__2025-06-17T04:00:00+00:00 [queued]>
[2025-06-18T15:48:29.968+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecommerce_daily_etl.process_and_load_to_snowflake scheduled__2025-06-17T04:00:00+00:00 [queued]>
[2025-06-18T15:48:29.968+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-06-18T15:48:29.977+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): process_and_load_to_snowflake> on 2025-06-17 04:00:00+00:00
[2025-06-18T15:48:29.983+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=949) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-18T15:48:29.984+0000] {standard_task_runner.py:63} INFO - Started process 951 to run task
[2025-06-18T15:48:29.984+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ecommerce_daily_etl', 'process_and_load_to_snowflake', 'scheduled__2025-06-17T04:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/ecommerce_daily_etl.py.py', '--cfg-path', '/tmp/tmpu4cfqlq2']
[2025-06-18T15:48:29.986+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask process_and_load_to_snowflake
[2025-06-18T15:48:30.022+0000] {task_command.py:426} INFO - Running <TaskInstance: ecommerce_daily_etl.process_and_load_to_snowflake scheduled__2025-06-17T04:00:00+00:00 [running]> on host fbc1e8976316
[2025-06-18T15:48:30.067+0000] {abstractoperator.py:725} ERROR - Exception rendering Jinja template for task 'process_and_load_to_snowflake', field '_application_args'. Template: ['--snowflake_url', '{{ conn.snowflake_default.host }}', '--snowflake_user', '{{ conn.snowflake_default.login }}', '--snowflake_password', '{{ conn.snowflake_default.password }}', '--snowflake_db', '{{ conn.snowflake_default.schema }}', '--snowflake_schema', '{{ conn.snowflake_default.extra_dejson.schema }}', '--snowflake_warehouse', '{{ conn.snowflake_default.extra_dejson.warehouse }}', '--snowflake_role', '{{ conn.snowflake_default.extra_dejson.role }}']
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/abstractoperator.py", line 717, in _do_render_template_fields
    rendered_content = self.render_template(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 179, in render_template
    return [self.render_template(element, context, jinja_env, oids) for element in value]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 169, in render_template
    return self._render(template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/abstractoperator.py", line 675, in _render
    return super()._render(template, context, dag=dag)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 126, in _render
    return render_template_to_string(template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 289, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 284, in render_template
    return "".join(nodes)
           ^^^^^^^^^^^^^^
  File "<template>", line 12, in root
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/sandbox.py", line 327, in getattr
    value = getattr(obj, attribute)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/context.py", line 133, in __getattr__
    self.var = Connection.get_connection_from_secrets(key)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snowflake_default` isn't defined
[2025-06-18T15:48:30.077+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2479, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2633, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context, jinja_env=jinja_env)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3094, in render_templates
    original_task.render_template_fields(context, jinja_env)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 1337, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/abstractoperator.py", line 717, in _do_render_template_fields
    rendered_content = self.render_template(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 179, in render_template
    return [self.render_template(element, context, jinja_env, oids) for element in value]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 169, in render_template
    return self._render(template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/abstractoperator.py", line 675, in _render
    return super()._render(template, context, dag=dag)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 126, in _render
    return render_template_to_string(template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 289, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 284, in render_template
    return "".join(nodes)
           ^^^^^^^^^^^^^^
  File "<template>", line 12, in root
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/sandbox.py", line 327, in getattr
    value = getattr(obj, attribute)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/context.py", line 133, in __getattr__
    self.var = Connection.get_connection_from_secrets(key)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snowflake_default` isn't defined
[2025-06-18T15:48:30.081+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=ecommerce_daily_etl, task_id=process_and_load_to_snowflake, run_id=scheduled__2025-06-17T04:00:00+00:00, execution_date=20250617T040000, start_date=20250618T154829, end_date=20250618T154830
[2025-06-18T15:48:30.095+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task process_and_load_to_snowflake (The conn_id `snowflake_default` isn't defined; 951)
[2025-06-18T15:48:30.118+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-18T15:48:30.133+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-18T15:48:30.135+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-06-18T17:26:31.692+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-18T17:26:31.712+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecommerce_daily_etl.process_and_load_to_snowflake scheduled__2025-06-17T04:00:00+00:00 [queued]>
[2025-06-18T17:26:31.719+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecommerce_daily_etl.process_and_load_to_snowflake scheduled__2025-06-17T04:00:00+00:00 [queued]>
[2025-06-18T17:26:31.719+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-06-18T17:26:31.730+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): process_and_load_to_snowflake> on 2025-06-17 04:00:00+00:00
[2025-06-18T17:26:31.739+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2250) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-18T17:26:31.745+0000] {standard_task_runner.py:63} INFO - Started process 2252 to run task
[2025-06-18T17:26:31.740+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ecommerce_daily_etl', 'process_and_load_to_snowflake', 'scheduled__2025-06-17T04:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/ecommerce_daily_etl.py.py', '--cfg-path', '/tmp/tmpmekgsyw0']
[2025-06-18T17:26:31.748+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask process_and_load_to_snowflake
[2025-06-18T17:26:31.897+0000] {task_command.py:426} INFO - Running <TaskInstance: ecommerce_daily_etl.process_and_load_to_snowflake scheduled__2025-06-17T04:00:00+00:00 [running]> on host fbc1e8976316
[2025-06-18T17:26:31.999+0000] {abstractoperator.py:725} ERROR - Exception rendering Jinja template for task 'process_and_load_to_snowflake', field '_application_args'. Template: ['--snowflake_url', '{{ conn.snowflake_default.host }}', '--snowflake_user', '{{ conn.snowflake_default.login }}', '--snowflake_password', '{{ conn.snowflake_default.password }}', '--snowflake_db', '{{ conn.snowflake_default.schema }}', '--snowflake_schema', '{{ conn.snowflake_default.extra_dejson.schema }}', '--snowflake_warehouse', '{{ conn.snowflake_default.extra_dejson.warehouse }}', '--snowflake_role', '{{ conn.snowflake_default.extra_dejson.role }}']
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/abstractoperator.py", line 717, in _do_render_template_fields
    rendered_content = self.render_template(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 179, in render_template
    return [self.render_template(element, context, jinja_env, oids) for element in value]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 169, in render_template
    return self._render(template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/abstractoperator.py", line 675, in _render
    return super()._render(template, context, dag=dag)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 126, in _render
    return render_template_to_string(template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 289, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 284, in render_template
    return "".join(nodes)
           ^^^^^^^^^^^^^^
  File "<template>", line 12, in root
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/runtime.py", line 857, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'schema'
[2025-06-18T17:26:32.005+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2479, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2633, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context, jinja_env=jinja_env)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3094, in render_templates
    original_task.render_template_fields(context, jinja_env)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 1337, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/abstractoperator.py", line 717, in _do_render_template_fields
    rendered_content = self.render_template(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 179, in render_template
    return [self.render_template(element, context, jinja_env, oids) for element in value]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 169, in render_template
    return self._render(template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/abstractoperator.py", line 675, in _render
    return super()._render(template, context, dag=dag)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 126, in _render
    return render_template_to_string(template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 289, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 284, in render_template
    return "".join(nodes)
           ^^^^^^^^^^^^^^
  File "<template>", line 12, in root
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/runtime.py", line 857, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'schema'
[2025-06-18T17:26:32.019+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=ecommerce_daily_etl, task_id=process_and_load_to_snowflake, run_id=scheduled__2025-06-17T04:00:00+00:00, execution_date=20250617T040000, start_date=20250618T172631, end_date=20250618T172632
[2025-06-18T17:26:32.031+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 5 for task process_and_load_to_snowflake ('dict object' has no attribute 'schema'; 2252)
[2025-06-18T17:26:32.041+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-18T17:26:32.053+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-18T17:26:32.055+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
